POST http://localhost:3001/user

{
    "name":"rowan",
    "surname":"rowan",
    "email":"abcde@email.com",
    "password":"123",
    "username":"fedcba"
}

###

DELETE http://localhost:3001/user

{
    "username":"321",
    "password":"123"
}

###

POST http://localhost:3001/auth/login

{
    "username":"callummclu",
    "password":"010305"
}

###

GET http://localhost:3001/user/callummclu

###

GET http://localhost:3001/profile/fedcba
